function printMenu()
  local wwidth = love.graphics.getWidth()
  local wheight = love.graphics.getHeight()
  love.graphics.setColor(255,255,255,255)
  love.graphics.rectangle("fill", 0, 0, wwidth, wwidth)
  love.graphics.setColor(222,222,222,255)
  love.graphics.rectangle("fill", 50, 50, wwidth-100, wheight-350 )
  love.graphics.setColor(0,0,0,255)
  love.graphics.print("One room, one air-traffic controller, 4 screens", love.window.toPixels(100), love.window.toPixels(100))
  love.graphics.print("Click anywhere to start the game", love.window.toPixels(120), love.window.toPixels(120))
  love.graphics.print("Press Esc or q to quit the game", love.window.toPixels(120), love.window.toPixels(140))
end
